### ISSUE TITLE
KeyError: 'test_ans_ind'

### ISSUE THREAD

**Issue by badripatro** [batra-mlp-lab/visdial-rl#8] opened 2018-07-11 15:41 UTC
Hi 
When I run this command 

-----------------------------------------------------------------

CUDA_VISIBLE_DEVICES=4 python train.py -useGPU -trainMode sl-qbot -enableVisdom 1 \
  -visdomServer http://127.0.0.1 -visdomServerPort 8098 -visdomEnv my-qbot-job

-----------------------------------------------------------------------

I  got this error  

-------------------------------------------------------------------

 File "train.py", line 39, in <module>
    dataset = VisDialDataset(params, splits)
  File "/home/badri/badripatro/workspace_project/visual_dialog/visdial-rl-master_v10/dataloader.py", line 149, in __init__
    self.prepareDataset(dtype)
  File "/visdial-rl-master_v10/dataloader.py", line 185, in prepareDataset
    self.data[dtype + '_ans_ind'] -= 1
KeyError: 'test_ans_ind'

--------------------------------------------------------------------------------
Should I change in  the "propro.py" file?

These are the keys present in "chat_processed_data.h5" file 

-------------------------------------------------------------------------------------------------

>>> f = h5py.File("chat_processed_data.h5")
>>> list(f)
['**ans_index_train', 'ans_index_val',** 'ans_length_test', 'ans_length_train', 'ans_length_val', 'ans_test', 'ans_train', 'ans_val', 'cap_length_test', 'cap_length_train', 'cap_length_val', 'cap_test', 'cap_train', 'cap_val', 'img_pos_test', 'img_pos_train', 'img_pos_val', 'num_rounds_test', 'opt_length_test', 'opt_length_train', 'opt_length_val', 'opt_list_test', 'opt_list_train', 'opt_list_val', 'opt_test', 'opt_train', 'opt_val', 'ques_length_test', 'ques_length_train', 'ques_length_val', 'ques_test', 'ques_train', 'ques_val']

------------------------------------------------------------------------------------------------

**Comment by kdexd** [comment] 2018-07-11 23:53
Hi @badripatro - it is a recently introduced bug in #8 mainly caused by a difference in schema between VisDial v0.5 and v1.0. We continue to offer out of the box support for v0.5 with this codebase.
I have opened #9, once it gets merged, you may pull from master and this issue will be resolved. :slightly_smiling_face:

**Comment by kdexd** [comment] 2018-07-12 15:56
Hi @badripatro: #9 is merged, please pull from master.

**Comment by badripatro** [comment] 2018-07-13 08:10
Thanks a lot.

**Closed as completed** 2018-07-13 15:07 UTC
